# Check the following link for mpv's default keybindings:
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf

# ==========    CUSTOM KEYBINDINGS    ==========

# GENERAL
k           cycle ontop

# VIDEO
d           cycle deband
D           cycle deinterlace
n           cycle video-unscaled
C           cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1" # cycle the video aspect ratio ("-1" is the container aspect)

# AUDIO
a           cycle audio
A           cycle audio down
WHEEL_UP    add volume 2
WHEEL_DOWN  add volume -2
UP          add volume 2
DOWN        add volume -2
x           add audio-delay -0.05
X           add audio-delay +0.05

# SUBTITLES
Shift+g     add sub-scale +0.05                     # increase the subtitle font size
Shift+f     add sub-scale -0.05                     # decrease the subtitle font size
E           add sub-gauss +0.1
R           add sub-gauss -0.1
z           add sub-delay -0.05                     # shift subtitles 50 ms earlier
Z           add sub-delay +0.05                     # shift subtitles 50 ms later
u           cycle sub-gray
U           cycle blend-subtitles
p           cycle sub-fix-timing
g           sub-reload
l           cycle-values sub-ass-override "yes" "force" "no"
